version: "3.3"

services:
  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3005:3000
    environment:
      DB_HOST: mongo
      DB_NAME: admin
    depends_on:
      - mongo
